(define (py-str-from-obj x)
  (define (py-str x)
    (let* ((x (mkstr x))
           (q (string #\"))
           (len (string-length x)))
      (let loop ((i 0)
                 (s ""))
        (if (< i len)
            (loop (+ i 1)
                  (string-append
                   s
                   (let ((c (string-ref x i)))
                     (case c
                       ((#\") (string #\\ #\"))
                       (else (string c))))))
            (string-append q s q)))))
  (cond ((equal? x #t) "True")
        ((equal? x #f) "False")
        ((string? x) (py-str x))
        ((symbol? x) (mkstr "shen.intern(" (py-str (symbol->string x)) ")"))
        ((pair? x)
         (let ((x (map py-str-from-obj x)))
           (mkstr "shen.dbg_list([" (strjoin x ", ") "])")))
        ((vector? x)
         (let ((x (map py-str-from-obj (vector->list x))))
           (mkstr "[" (strjoin x ", ") "]")))
        (#t (mkstr x))))

(define (py-from-test-defs defs var)
  (let loop ((defs defs)
             (acc '()))
    (if (and (pair? defs) (pair? (cdr defs)) (pair? (cddr defs)))
        (let* ((call (car defs))
               (expected (caddr defs))
               (s (strjoin (cons (py-str-from-obj (mkstr (car call)))
                                 (map py-str-from-obj (cdr call)))
                           ", ")))
          (loop (cdddr defs)
                (cons (mkstr "((" s ",), " (py-str-from-obj expected) ")")
                      acc)))
        (mkstr var #\newline "    return (" #\newline "  "
               (strjoin (reverse acc) (mkstr "," #\newline "  "))
               #\newline ")" #\newline))))

(define (py-save)
  (with-output-to-file
    "~/dev/shen/shen-py/tests/test_def.py"
    (lambda ()
      (display (py-from-test-defs t1.defs "def mkcases(shen):")))))
